### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by ThePagel** [MoochMcGee/Emotionless#2]
I bet if you approach the community again and politely ask for help you might get some support to get past any hurdles you're stuck on. It would probably also help if you admit you were harsh on pcsx2 and understand why you got the backlash last time (no matter if you actually feel that way). Ps2 on retroarch would be amazing, hope you haven't given up.

**Comment by MoochMcGee** [comment]
I understand why I got the backlash last time, but I'm not going to be any
less harsh on PCSX2 than I was then. They've started implementing even more
game-specific hacks to bypass bugs that they could conceivably fix on their
own, just given more time. I also have no respect for Gregory given that he
made GSDX's OpenGL backend REQUIRE OpenGL 4.5, rather than just
implementing a fallback. Actually, he REMOVED a fallback to make that
happen! So fuck the PCSX2 team.

**Comment by ThePagel** [comment]
I personally agree with you but since I have very little programming ability I have no right to come out and hate on the only truly working emulator for ps2. I hope someday we have a alternative that is more accuracy focused that plays most games as well or better than pcsx2. You and the Play! guy seem to be the only ones interested in attempting this.

**Comment by Shadow3342** [comment]
how do i run the program. i'm an idiot i never used github before or have no knowledge of how to run the program. could you help?
